version: '3.8'

services:
  kafka-ui:
    image: tchiotludo/akhq
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka1:29092,kafka2:29093,kafka3:29094"
